if: branch !~ ^v\d
language: node_js
node_js: node
matrix:
  include:
  - dist: xenial
    after_success: npm run-script coverage && npx istanbul-coveralls
  - os: windows
    script: npm run-script test-only
